// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkfijttdhgkdzruygylq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrZmlqdHRkaGdrZHpydXlneWxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDcxODIsImV4cCI6MjA2OTI4MzE4Mn0.rVz2iZiu4xSYSqPjQgpU2XI_2do6gzGhlNBKUq1-a58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});