# Generated by Django 5.2.8 on 2025-11-17 08:52

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Provider Information',
                'verbose_name_plural': 'Providers Information',
            },
        ),
        migrations.CreateModel(
            name='ProviderConnection',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('api_key', models.CharField(max_length=2550)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.provider')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderConnectionConfig',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('config_name', models.CharField(max_length=100)),
                ('config_value', models.CharField(max_length=100)),
                ('provider_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.providerconnection')),
            ],
        ),
    ]
