# Generated by Django 5.2.8 on 2025-12-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="provider",
            options={"verbose_name": "Provider", "verbose_name_plural": "Providers"},
        ),
        migrations.AlterModelOptions(
            name="providerconnection",
            options={
                "verbose_name": "Connection",
                "verbose_name_plural": "Connections",
            },
        ),
        migrations.AlterModelOptions(
            name="providerconnectionconfig",
            options={
                "verbose_name": "Connection Config",
                "verbose_name_plural": "Connection Configs",
            },
        ),
    ]
