# Generated by Django 5.2.8 on 2025-12-13 09:07

import django.core.validators
import django.db.models.deletion
import django_mongodb_backend.fields
import reporting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlertEmbedded",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("performance", "performance"),
                            ("security", "security"),
                            ("system", "system"),
                            ("disk", "disk"),
                            ("network", "network"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "info"),
                            ("warning", "warning"),
                            ("critical", "critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BandwidthEmbedded",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "download",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "healthScore",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("devices", models.PositiveIntegerField(default=0)),
                (
                    "patchCompliance",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "securityScore",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("backupStatus", models.CharField(max_length=50)),
                ("securityStatus", models.CharField(max_length=50)),
                (
                    "networkUptime",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("lastUpdated", models.DateTimeField()),
                ("criticalThreats", models.PositiveIntegerField(default=0)),
                ("patchingIssues", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PatchData",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.IntegerField(unique=True)),
                ("device", models.CharField(max_length=255)),
                ("client", models.CharField(max_length=255)),
                ("site", models.CharField(max_length=255)),
                ("patch", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Installed", "Installed"),
                            ("Pending", "Pending"),
                            ("Failed", "Failed"),
                            ("Not Applicable", "Not Applicable"),
                            ("Installing", "Installing"),
                            ("Reboot Required", "Reboot Required"),
                        ],
                        max_length=30,
                    ),
                ),
                ("discovered_install_date", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ProgressBar",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                (
                    "width",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BranchTicketStats",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch", models.CharField(max_length=255)),
                ("total", models.PositiveIntegerField(default=0)),
                ("open", models.PositiveIntegerField(default=0)),
                ("resolved", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_ticket_stats",
                        to="reporting.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BackupDevice",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deviceName", models.CharField(max_length=255)),
                ("computerName", models.CharField(max_length=255)),
                (
                    "deviceType",
                    models.CharField(
                        choices=[
                            ("Workstation", "Workstation"),
                            ("Server", "Server"),
                            ("Documents", "Documents"),
                            ("Not Installed", "Not Installed"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "selectedSize",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "usedStorage",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "backupStatus",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("CompletedWithErrors", "CompletedWithErrors"),
                            ("Failed", "Failed"),
                            ("InProcess", "InProcess"),
                            ("No backups", "No backups"),
                        ],
                        max_length=40,
                    ),
                ),
                ("errors", models.PositiveIntegerField(default=0)),
                ("lastBackup", models.DateTimeField()),
                (
                    "progressBars",
                    django_mongodb_backend.fields.ArrayField(
                        base_field=django_mongodb_backend.fields.EmbeddedModelField(
                            embedded_model=reporting.models.ProgressBar
                        ),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_devices",
                        to="reporting.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AntivirusData",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.IntegerField(unique=True)),
                ("device_name", models.CharField(max_length=255)),
                ("av_product_name", models.CharField(max_length=255)),
                ("av_status", models.CharField(max_length=100)),
                ("threat_count", models.PositiveIntegerField(default=0)),
                ("last_update", models.DateTimeField()),
                ("last_scan", models.DateTimeField()),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antivirus_rows",
                        to="reporting.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("workstation", "workstation"),
                            ("server", "server"),
                            ("laptop", "laptop"),
                            ("mobile", "mobile"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "online"),
                            ("offline", "offline"),
                            ("warning", "warning"),
                            ("critical", "critical"),
                        ],
                        max_length=30,
                    ),
                ),
                ("os", models.CharField(max_length=255)),
                ("lastSeen", models.DateTimeField()),
                (
                    "uptime",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "cpu",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "memory",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "disk",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("location", models.CharField(max_length=255)),
                ("user", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "alerts",
                    django_mongodb_backend.fields.ArrayField(
                        base_field=django_mongodb_backend.fields.EmbeddedModelField(
                            embedded_model=reporting.models.AlertEmbedded
                        ),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices_list",
                        to="reporting.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DevicePatchStatus",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deviceId", models.CharField(max_length=255)),
                ("deviceName", models.CharField(max_length=255)),
                ("os", models.CharField(max_length=255)),
                ("totalPatches", models.PositiveIntegerField(default=0)),
                ("installedPatches", models.PositiveIntegerField(default=0)),
                ("pendingPatches", models.PositiveIntegerField(default=0)),
                ("failedPatches", models.PositiveIntegerField(default=0)),
                (
                    "compliancePercentage",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("lastScan", models.DateTimeField()),
                (
                    "riskLevel",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_patch_statuses",
                        to="reporting.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NetworkDevice",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("gateway", "gateway"),
                            ("switch", "switch"),
                            ("access_point", "access_point"),
                            ("camera", "camera"),
                            ("phone", "phone"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "online"),
                            ("offline", "offline"),
                            ("warning", "warning"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "uptime",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("ip", models.GenericIPAddressField()),
                ("model", models.CharField(max_length=255)),
                ("firmware", models.CharField(max_length=255)),
                ("clients", models.PositiveIntegerField(default=0)),
                (
                    "bandwidth",
                    django_mongodb_backend.fields.EmbeddedModelField(
                        embedded_model=reporting.models.BandwidthEmbedded
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_devices",
                        to="reporting.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NetworkEvent",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deviceName", models.CharField(max_length=255)),
                (
                    "eventType",
                    models.CharField(
                        choices=[
                            ("connection_lost", "connection_lost"),
                            ("high_usage", "high_usage"),
                            ("firmware_update", "firmware_update"),
                            ("client_connected", "client_connected"),
                            ("client_disconnected", "client_disconnected"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "info"),
                            ("warning", "warning"),
                            ("critical", "critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("description", models.TextField()),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_events",
                        to="reporting.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patch",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deviceName", models.CharField(max_length=255)),
                ("patchName", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("security", "security"),
                            ("feature", "feature"),
                            ("bugfix", "bugfix"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("installed", "installed"),
                            ("failed", "failed"),
                            ("scheduled", "scheduled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("releaseDate", models.DateTimeField()),
                ("installDate", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patches",
                        to="reporting.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reporting",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid_field",
                    models.CharField(
                        default=reporting.models.generate_uuid_string,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "ref_code",
                    models.CharField(
                        default=reporting.models.generate_random_string,
                        editable=False,
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecuritySummary",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("totalDevices", models.PositiveIntegerField(default=0)),
                ("antivirusInstalled", models.PositiveIntegerField(default=0)),
                ("sentinelOneInstalled", models.PositiveIntegerField(default=0)),
                ("protectedDevices", models.PositiveIntegerField(default=0)),
                ("unprotectedDevices", models.PositiveIntegerField(default=0)),
                ("activeThreats", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_summaries",
                        to="reporting.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SentinelOneData",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.IntegerField(unique=True)),
                ("endpoints", models.CharField(max_length=255)),
                ("site", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=100)),
                ("classification", models.CharField(max_length=100)),
                ("confidence_level", models.CharField(max_length=100)),
                ("threat_details", models.TextField()),
                ("analyst_verdict", models.CharField(max_length=100)),
                ("incident_status", models.CharField(max_length=100)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentinelone_rows",
                        to="reporting.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketData",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("In Progress", "In Progress"),
                            ("Resolved", "Resolved"),
                            ("Closed", "Closed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("branch", models.CharField(max_length=255)),
                ("user", models.CharField(max_length=255)),
                ("created", models.DateTimeField()),
                ("updated", models.DateTimeField()),
                ("category", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="reporting.customer",
                    ),
                ),
            ],
        ),
    ]
