# Generated by Django 5.2.8 on 2026-02-02 00:06

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncProvider",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="SyncClient",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clientid", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("creation_date", models.CharField(blank=True, max_length=50)),
                ("device_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_clients",
                        to="reporting.syncprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["provider", "clientid"],
            },
        ),
        migrations.CreateModel(
            name="SyncSite",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("siteid", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_sites",
                        to="reporting.syncclient",
                    ),
                ),
            ],
            options={
                "ordering": ["client", "siteid"],
            },
        ),
        migrations.CreateModel(
            name="SyncDevice",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("status", models.CharField(default="unknown", max_length=50)),
                ("username", models.CharField(blank=True, max_length=255)),
                (
                    "device_type",
                    models.CharField(
                        choices=[("server", "server"), ("workstation", "workstation")],
                        max_length=20,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_devices",
                        to="reporting.syncclient",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_devices",
                        to="reporting.syncsite",
                    ),
                ),
            ],
            options={
                "ordering": ["client", "site", "external_id"],
            },
        ),
        migrations.CreateModel(
            name="SyncFailingCheck",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("start_date", models.CharField(blank=True, max_length=50)),
                ("start_time", models.CharField(blank=True, max_length=50)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_failing_checks",
                        to="reporting.syncclient",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_failing_checks",
                        to="reporting.syncdevice",
                    ),
                ),
            ],
            options={
                "ordering": ["client", "start_date", "start_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client", "device", "start_date", "start_time"),
                        name="unique_sync_failing_check_client_device_datetime",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="syncclient",
            constraint=models.UniqueConstraint(
                fields=("provider", "clientid"),
                name="unique_sync_client_provider_clientid",
            ),
        ),
        migrations.AddConstraint(
            model_name="syncsite",
            constraint=models.UniqueConstraint(
                fields=("client", "siteid"), name="unique_sync_site_client_siteid"
            ),
        ),
        migrations.AddConstraint(
            model_name="syncdevice",
            constraint=models.UniqueConstraint(
                fields=("client", "site", "external_id"),
                name="unique_sync_device_client_site_id",
            ),
        ),
    ]
